version: '3'
services:
    app:
      build: .
      hostname: app
      container_name: app_front
      ports:
        - "3001:3000"
      healthcheck:
        test: ['CMD', 'curl', '-f', 'http://localhost:3001']
        interval: 1m30s
        timeout: 10s
        retries: 3
